version: "3.7"
services:
  mongo:
    image: mongo
    container_name: mongotest
    restart: always
    ports:
      - "27017:27017"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
  app-web:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
  
  bot:
    depends_on:
      - mongo
    build: ./bot
    